
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  #    database-platform: org.hibernate.dialect.Oracle12cDialect
  #    open-in-view: false

  datasource:
    url: jdbc:mariadb://localhost:43306/sampledb
    driver-class-name: org.mariadb.jdbc.Driver
    username: week5_user
    password: 1234

  mail :
    host : smtp.gmail.com
    port : 587
    username: shcrlk12@gmail.com
    password: xwcqofslpzhpznwz
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML5
    cache: false

server:
  port: 8080

logging:
  level:
    root: info

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl